var sounda = new Audio();
    sounda.src = "assets/sound/huruf/a.mp3"
var soundb = new Audio();
    soundb.src = "assets/sound/huruf/b.mp3"
    var soundc = new Audio();
    soundc.src = "assets/sound/huruf/c.mp3"
        var soundd = new Audio();
    soundd.src = "assets/sound/huruf/d.mp3"
     var sounde = new Audio();
    sounde.src = "assets/sound/huruf/e.mp3"
var soundf = new Audio();
    soundf.src = "assets/sound/huruf/f.mp3"
    var soundg = new Audio();
    soundg.src = "assets/sound/huruf/g.mp3"
     var soundh = new Audio();
    soundh.src = "assets/sound/huruf/h.mp3"
     var soundi = new Audio();
    soundi.src = "assets/sound/huruf/i.mp3"
    var soundj = new Audio();
    soundj.src = "assets/sound/huruf/j.mp3"
    var soundk = new Audio();
    soundk.src = "assets/sound/huruf/k.mp3"
    var soundl = new Audio();
    soundl.src = "assets/sound/huruf/l.mp3"
     var soundm = new Audio();
    soundm.src = "assets/sound/huruf/m.mp3"
     var soundn = new Audio();
    soundn.src = "assets/sound/huruf/n.mp3"
     var soundo = new Audio();
    soundo.src = "assets/sound/huruf/o.mp3"
    var soundp = new Audio();
    soundp.src = "assets/sound/huruf/p.mp3"
    var soundq = new Audio();
    soundq.src = "assets/sound/huruf/q.mp3"
    var soundr = new Audio();
    soundr.src = "assets/sound/huruf/r.mp3"
     var sounds = new Audio();
    sounds.src = "assets/sound/huruf/s.mp3"
       var soundt = new Audio();
    soundt.src = "assets/sound/huruf/t.mp3"
        var soundu = new Audio();
    soundu.src = "assets/sound/huruf/u.mp3"
            var soundv = new Audio();
    soundv.src = "assets/sound/huruf/v.mp3"
     var soundw = new Audio();
    soundw.src = "assets/sound/huruf/w.mp3"
         var soundx = new Audio();
    soundx.src = "assets/sound/huruf/x.mp3"
         var soundy = new Audio();
    soundy.src = "assets/sound/huruf/y.mp3"
             var soundz = new Audio();
    soundz.src = "assets/sound/huruf/z.mp3"

    var sound1 = new Audio();
    sound1.src = "assets/sound/angka/1.mp3"
        var sound2 = new Audio();
    sound2.src = "assets/sound/angka/2.mp3"
        var sound3 = new Audio();
    sound3.src = "assets/sound/angka/3.mp3"
        var sound4 = new Audio();
    sound4.src = "assets/sound/angka/4.mp3"
        var sound5 = new Audio();
    sound5.src = "assets/sound/angka/5.mp3"
        var sound6 = new Audio();
    sound6.src = "assets/sound/angka/6.mp3"
        var sound7 = new Audio();
    sound7.src = "assets/sound/angka/7.mp3"
        var sound8 = new Audio();
    sound8.src = "assets/sound/angka/8.mp3"
        var sound9 = new Audio();
    sound9.src = "assets/sound/angka/9.mp3"
        var sound0 = new Audio();
    sound0.src = "assets/sound/angka/0.mp3"